# 3.4. Ejemplo 3.3: más de tres galgas extensométricas

|Quién |Correo | Fecha | Qué hizo |
| ---  |---    | ---   | ---      |
|Michael Heredia Pérez | <mherediap@unal.edu.co> | Julio 16, 2022 | Conversión de código de MATLAB a Python|
|Juan Nicolás Ramírez  | <jnramirezg@unal.edu.co> | Septiembre 24, 2022 | Adecuando código|
|Michael Heredia Pérez | <mherediap@unal.edu.co> | Marzo 30, 2023 | Mejorando la explicación del procedimiento|
|Diego Andrés Alvarez Marín | <daalvarez@unal.edu.co> | Marzo 7, 2024 | Mejorando los comentarios, incluyendo comandos nuevos |

$$
\newcommand{\ve}[1]{{\vec{\boldsymbol{#1}}}}
\newcommand{\ma}[1]{{\boldsymbol{#1}}}
\newcommand{\hve}[1]{{\,\hat{\!\boldsymbol{#1}}}}
\newcommand{\tr}{\operatorname{tr}}
$$

Suponga que tenemos cinco galgas extensométricas, a saber A, B, C, D y E, ubicadas sobre el mismo plano a unas inclinaciones de 0°, 72°, 144°, 216° y 288° tal y como se ilustra en la figura; las deformaciones medidas por las galgas fueron 3.0012×10⁻⁴, 3.4521×10⁻⁴, 1.4935×10⁻³, −4.0924×10⁻⁴ y 1.5207×10⁻³, respectivamente; dichas lecturas no son precisas, ya que tienen unos pequeños errores de medición. 

* Dadas las lecturas anteriores, estime la mejor aproximación posible de las deformaciones $\varepsilon_x$ , $\varepsilon_y$ y $\varepsilon_{xy}$ .

<img src="3.04_ejem_3.3_roseta_5_galgas.png" width="400">

Importamos de la librería ```numpy``` para cálculos numéricos, algunas funciones:

In [1]:
from numpy import sin, cos, deg2rad, array
from numpy.linalg import inv, pinv, lstsq, norm

A partir de la formulación del problema definimos las siguientes constantes:

In [2]:
# Medición              Ángulo [°]
eA =  3.0012e-4;        tA =  0
eB =  3.4521e-4;        tB =  72
eC =  1.4935e-3;        tC = 144
eD = -4.0924e-4;        tD = 216
eE =  1.5207e-3;        tE = 288

Usando la ecuación 

$$\varepsilon_{x'} = \varepsilon_{x} \cos^{2}{\left(\theta \right)} + \varepsilon_{y} \sin^{2}{\left(\theta \right)}+\varepsilon_{xy} \sin{\left(2\theta \right)},$$ 

podemos escribir $\varepsilon_A$, $\varepsilon_B$, $\varepsilon_C$, $\varepsilon_D$ y $\varepsilon_E$ en función de $\varepsilon_x$, $\varepsilon_y$, $\varepsilon_{xy}$ y el ángulo de inclinación $\theta$, de manera que:

$$\varepsilon_{A} = \varepsilon_{x'}(\theta_A) = \varepsilon_{x} \cos^{2}{\left(\theta_A \right)} + \varepsilon_{y} \sin^{2}{\left(\theta_A \right)}+\varepsilon_{xy} \sin{\left(2\theta_A \right)}$$
$$\varepsilon_{B} = \varepsilon_{x'}(\theta_B) = \varepsilon_{x} \cos^{2}{\left(\theta_B \right)} + \varepsilon_{y} \sin^{2}{\left(\theta_B \right)}+\varepsilon_{xy} \sin{\left(2\theta_B \right)}$$
$$\varepsilon_{C} = \varepsilon_{x'}(\theta_C) = \varepsilon_{x} \cos^{2}{\left(\theta_C \right)} + \varepsilon_{y} \sin^{2}{\left(\theta_C \right)}+\varepsilon_{xy} \sin{\left(2\theta_C \right)}$$
$$\varepsilon_{D} = \varepsilon_{x'}(\theta_D) = \varepsilon_{x} \cos^{2}{\left(\theta_D \right)} + \varepsilon_{y} \sin^{2}{\left(\theta_D \right)}+\varepsilon_{xy} \sin{\left(2\theta_D \right)}$$
$$\varepsilon_{E} = \varepsilon_{x'}(\theta_E) = \varepsilon_{x} \cos^{2}{\left(\theta_E \right)} + \varepsilon_{y} \sin^{2}{\left(\theta_E \right)}+\varepsilon_{xy} \sin{\left(2\theta_E \right)}$$

El sistema de ecuaciones anterior se puede escribir como:

$$\begin{bmatrix}\varepsilon_{A}\\ 
                      \varepsilon_{B}\\
                      \varepsilon_{C}\\
                      \varepsilon_{D}\\
                      \varepsilon_{E}\\
\end{bmatrix} =
\begin{bmatrix}\cos^{2}{\left(\theta_A \right)} & \sin^{2}{\left(\theta_A \right)} & \sin{\left(2\theta_A \right)}\\
                    \cos^{2}{\left(\theta_B \right)} & \sin^{2}{\left(\theta_B \right)} & \sin{\left(2\theta_B \right)}\\
                    \cos^{2}{\left(\theta_C \right)} & \sin^{2}{\left(\theta_C \right)} & \sin{\left(2\theta_C \right)}\\ 
                    \cos^{2}{\left(\theta_D \right)} & \sin^{2}{\left(\theta_D \right)} & \sin{\left(2\theta_D \right)}\\ 
                    \cos^{2}{\left(\theta_E \right)} & \sin^{2}{\left(\theta_E \right)} & \sin{\left(2\theta_E \right)}\\ \end{bmatrix}
\begin{bmatrix}
\varepsilon_{x} \\ \varepsilon_{y}\\ \gamma_{xy} 
\end{bmatrix}
$$


esto es un sistema de ecuaciones de la forma $\ve{b} = \ma{A} \ve{x}$.

Sin embargo, este sistema de ecuaciones no se puede resolver de la forma usual premultiplicando por $\ma{A}^{−1}$ a ambos lados de la igualdad, ya que la matriz $\ma{A}$ no es cuadrada (es una matriz de 5x3), y en consecuencia su inversa no existe; sin embargo, se puede resolver utilizando la formulación de mínimos cuadrados, de modo que:

$$\ve{x} = \underbrace{(\ma{A}^T\ma{A})^{-1}\ma{A}^T}_{\ma{A}^\dagger}\ve{b}$$

donde $\ma{A}^\dagger$ es la llamada [pseudoinversa de Moore-Penrose](https://en.wikipedia.org/wiki/Moore-Penrose_inverse).

En Python no tenemos la función ```cosd()``` ni ```sind()```, las cuales calculan cosenos y senos, respectivamente, con el argumento en grados (*degrees*), podríamos usar la función ```numpy.deg2rad()``` para convertir de grados a radianes y hacer el cálculo, o construir las funciones simplemente:

In [3]:
cosd = lambda t : cos(deg2rad(t)) # coseno de ángulos en grados
sind = lambda t : sin(deg2rad(t)) # seno   de ángulos en grados

Construimos la matriz: 

$$
\ma{A}
=
\begin{bmatrix}\cos^{2}{\left(\theta_A \right)} & \sin^{2}{\left(\theta_A \right)} & \sin{\left(2\theta_A \right)}\\
                    \cos^{2}{\left(\theta_B \right)} & \sin^{2}{\left(\theta_B \right)} & \sin{\left(2\theta_B \right)}\\
                    \cos^{2}{\left(\theta_C \right)} & \sin^{2}{\left(\theta_C \right)} & \sin{\left(2\theta_C \right)}\\ 
                    \cos^{2}{\left(\theta_D \right)} & \sin^{2}{\left(\theta_D \right)} & \sin{\left(2\theta_D \right)}\\ 
                    \cos^{2}{\left(\theta_E \right)} & \sin^{2}{\left(\theta_E \right)} & \sin{\left(2\theta_E \right)}\end{bmatrix}$$

In [4]:
A = array([[ cosd(tA)**2,   sind(tA)**2,   sind(2*tA) ],
           [ cosd(tB)**2,   sind(tB)**2,   sind(2*tB) ],
           [ cosd(tC)**2,   sind(tC)**2,   sind(2*tC) ],
           [ cosd(tD)**2,   sind(tD)**2,   sind(2*tD) ],
           [ cosd(tE)**2,   sind(tE)**2,   sind(2*tE) ]])

A

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.0954915 ,  0.9045085 ,  0.58778525],
       [ 0.6545085 ,  0.3454915 , -0.95105652],
       [ 0.6545085 ,  0.3454915 ,  0.95105652],
       [ 0.0954915 ,  0.9045085 , -0.58778525]])

Construimos el vector: 

$$
\ve{b}=\begin{pmatrix}
\varepsilon_{A}& 
\varepsilon_{B}&
\varepsilon_{C}&
\varepsilon_{D}&
\varepsilon_{E}
\end{pmatrix}^T
$$

In [5]:
b = array([eA, eB, eC, eD, eE])

b

array([ 0.00030012,  0.00034521,  0.0014935 , -0.00040924,  0.0015207 ])

Aplicamos la ecuación $$\ve{x} = (\ma{A}^T\ma{A})^{-1}\ma{A}^T\ve{b}$$ 

**Nota:** tener en cuenta que tanto ```M.T``` como ```numpy.transpose(M)``` permiten calcular la transpuesta de una matriz ```M```.

In [6]:
x1 = (inv(A.T@A) @ A.T) @ b

x1

array([ 0.00030031,  0.00099981, -0.00100022])

La función ```numpy.linalg.pinv()``` se puede utilizar para calcular $\ma{A}^\dagger$, de modo que:

In [7]:
x2 = pinv(A)@b

x2

array([ 0.00030031,  0.00099981, -0.00100022])

En Matlab existe el comando ```A\b``` para resolver en forma eficiente este sistema de ecuaciones. Su equivalente en Python es el comando ```numpy.linalg.lstsq```:

In [8]:
x3, residuals, rank, s = lstsq(A, b, rcond=None)

x3

array([ 0.00030031,  0.00099981, -0.00100022])

En conclusión, la solución al problema de mínimos cuadrados es:

$$\left[\begin{matrix}\varepsilon_{x} \\ \varepsilon_{y}\\ \varepsilon_{xy} \end{matrix}\right] = \left[\begin{matrix}3.0031\times10^{-4} \\ 9.9981\times10^{-4}\\ -1.0002\times10^{-3} \end{matrix}\right]$$

Calculamos los errores entre las tres respuestas:

In [9]:
norm(x1 - x2)

6.594944350062753e-19

In [10]:
norm(x1 - x3)

7.19178360604521e-19

In [11]:
norm(x2 - x3)

2.42434975903054e-19

y observamos que al ser el error tan pequeño, ambas se pueden considerar iguales.