# 3.4. Ejercicio 3.1. Roseta de deformación de tres galgas

|Quién | Correo |Fecha | Qué hizo |
| ---  | ---    | ---  | ---      |
|Michael Heredia Pérez | <mherediap@unal.edu.co> | Julio 16, 2022 | Conversión de código de MAXIMA a Python|
|Juan Nicolás Ramírez | <jnramirezg@unal.edu.co> | Septiembre 24, 2022 | Adecuando código|
|Michael Heredia Pérez | <mherediap@unal.edu.co> | Marzo 30, 2023 | Explicando mejor el procedimiento |
|Diego Andrés Alvarez Marín | <mherediap@unal.edu.co> | Marzo 8, 2024 | Comentarios adicionales |

$$
\newcommand{\ve}[1]{{\vec{\boldsymbol{#1}}}}
\newcommand{\ma}[1]{{\boldsymbol{#1}}}
\newcommand{\hve}[1]{{\,\hat{\!\boldsymbol{#1}}}}
\newcommand{\tr}{\operatorname{tr}}
$$

In [1]:
from numpy.linalg import norm
from numpy import array, cross, c_

Se define la función vector unitario:

$$
\hve{v} = \frac{\ve{v}}{\|\ve{v}\|}
$$

In [2]:
vector_unitario = lambda v : v/norm(v)

Se calculan las direcciones para los vectores $\hve{e}_1'$, $\hve{e}_2'$ y $\hve{e}_3'$

In [3]:
# Identificamos 3 puntos.
p_dir_x             = array([1, -2, -3])
dir_normal_plano    = array([2,  1,  5])
origen_coord_xpypzp = array([4,  2, -5])

# La dirección de e1gp respecto al nuevo sistema de coordenadas se calcula como 
# la distancia normalizada entre (2, 1, 5) y (4, 2, -5), a.k.a. el nuevo oriden 
# de coordenadas. 
e1gp = vector_unitario(p_dir_x - origen_coord_xpypzp)

p_dir_x - origen_coord_xpypzp

array([-3, -4,  2])

In [4]:
# e3gp está dado respecto a la base xyz, además sale del origen de coordenadas 
# x'y'z' dado por le punto (4,2,-5), de hecho forman un plano, así que 
# simplemente se normaliza.
e3gp = vector_unitario(dir_normal_plano)

Tenemos en cuenta que:

$$\hve{e}_2' = \hve{e}_3' \times \hve{e}_1' = -\hve{e}_1' \times \hve{e}_3'$$

ya que los vectores deben formar un sistema de coordenadas de la mano derecha:

In [5]:
e2gp = cross(e3gp, e1gp)          

Se define la matriz de transformación $\ma{T} = \left[\hve{e}_1', \hve{e}_2', \hve{e}_3'\right]$ concatenando los vectores columna:

In [6]:
T = c_[e1gp, e2gp, e3gp]

T

array([[-0.55708601,  0.74586985,  0.36514837],
       [-0.74278135, -0.64416033,  0.18257419],
       [ 0.37139068, -0.16951588,  0.91287093]])

Sabiendo que la lectura de las galgas es:

In [7]:
eA =    1e-3  
eB =  2.1e-3  
eC = -1.7e-3  

Determinamos las deformaciones $\varepsilon_x'$, $\varepsilon_y'$ y $\varepsilon_{x'y'}$ a partir de la lectura de las galgas, utilizando las ecuaciones:

$\varepsilon_{x} = \varepsilon_{A}$

$\varepsilon_{y} = \varepsilon_{C}$

$\varepsilon_{xy} = \varepsilon_{B}-\frac{\varepsilon_{A}+\varepsilon_{C}}{2}$

<img src="3.04_ejem_3.1_roseta_3_galgas.png" width="400">

In [8]:
e_xp   = eA
e_yp   = eC 
e_xpyp = eB - (eA + eC)/2

Se define la matriz de deformaciones $\ma{\varepsilon}'$ en $x'$, $y'$, $z'$. Aquí estamos teniendo en cuenta el estado de deformación plana $\varepsilon_{z'} = \varepsilon_{x'z'} =  \varepsilon_{y'z'} = 0$.

In [9]:
epsilonP = array([[e_xp,   e_xpyp,        0],
                  [e_xpyp,   e_yp,        0],
                  [0,           0,        0]])

Calculamos la matriz de deformaciones $\ma{\varepsilon}$ en el sistema de coordenadas globales $x$, $y$, $z$ mediante la ecuación $$\ma{\varepsilon} = \ma{T}\ma{\varepsilon}'\ma{T}^T$$

In [10]:
epsilon = T @ epsilonP @ T.T
epsilon

array([[-0.00267142,  0.00075242,  0.00091808],
       [ 0.00075242,  0.00219083, -0.00073913],
       [ 0.00091808, -0.00073913, -0.00021941]])

Extraemos todas las deformaciones:

In [11]:
print(f"e_x  = {epsilon[0][0]: .8f}")
print(f"e_y  = {epsilon[1][1]: .8f}")
print(f"e_z  = {epsilon[2][2]: .8f}") 
print(f"e_xy = {epsilon[0][1]: .8f}") 
print(f"e_xz = {epsilon[0][2]: .8f}") 
print(f"e_yz = {epsilon[1][2]: .8f}")

e_x  = -0.00267142
e_y  =  0.00219083
e_z  = -0.00021941
e_xy =  0.00075242
e_xz =  0.00091808
e_yz = -0.00073913


Observe que en el sistema de coordenadas gloables si existe la deformación longitudinal $\varepsilon_z$ y las deformaciones angulares en el plano $\varepsilon_{xz}$ y $\varepsilon_{yz}$. 